### ISSUE TITLE
support multiple validation functions

### ISSUE THREAD

**Issue by gregcaporaso** [biocore/Keemei#19]
It will be important for the set of rules that are applied to be customizable. For example, Qiita has different requirements for its *sample template* and *prep template* (biocore/qiita#933) than QIIME 1.x has for its mapping files.

What probably makes the most sense for this would be if there were multiple ``validate`` functions, which were tool/version-specific (e.g., QIIME 1.9.x, Qiita 0.1.x, ...), and if the user could choose to validate with one or more of these from within the Google Spreadsheets interface.

**Comment by jairideout** [comment]
Great idea! Ideally this will be fully customizable so that other formats can be supported, and we can provide tool/version-specific validators for QIIME, Qiita, etc. that are pre-configured for users.

**Comment by jairideout** [comment]
The code is now factored to support multiple validation formats. Closing as we have more specific issues for formats we plan to support.
