### ISSUE TITLE
create demo youtube video

### ISSUE THREAD

**Issue by jairideout** [biocore/Keemei#45]
Optional if add-on is accepted for publication in the web store.

**Comment by jairideout** [comment]
Remember to add video link in web store release.

**Comment by odetomyday** [comment]
Can I have details about what you would like to see included in such a video?

**Comment by jairideout** [comment]
Thanks for your interest in a Keemei video @odetomyday! (BTW I've been following the discussion in https://github.com/biocore/qiime/issues/2129)

Here's what I was thinking for the video. I'm pulling most of the points from http://keemei.qiime.org, there's much more detail there:

- Brief intro: describe what Keemei is and why you'd want to use it. [This section](http://keemei.qiime.org/#why) of the website covers that briefly; [the preprint](https://peerj.com/preprints/1670/) goes into more detail.
- Installation: show how to install Keemei through either the Chrome Web Store link provided on the website or a spreadsheet that's already open. Instructions for both install methods are in [this section](http://keemei.qiime.org/#install) of the website. Mention that you'll always have the latest version of Keemei; updates are installed automatically.
- Warning to users about cell background colors and notes: paraphrase the warning found at the bottom of the [install instructions](http://keemei.qiime.org/#install).
- Demo usage: basically walk through the instructions in [this section](http://keemei.qiime.org/#usage) of the website using the example datasets provided there. Show how to discover invalid cells via the sidebar and visually in the spreadsheet. Show how to quickly navigate to an invalid cell from the sidebar. Show how to fix some cells and rerun Keemei to display updated results. Show how to clear validation status.
- Export for use with QIIME: `File > Download as > Tab-separated values`. It'd be cool to show how to use QIIME's `load_remote_mapping_file.py` script (tutorial [here](http://qiime.org/tutorials/remote_mapping_files.html)) to load a mapping file from the command line, but not critical for this video.
- Refer users to http://keemei.qiime.org for more info (e.g., getting help, providing feedback, FAQs, etc.). I don't want to include this info in the video because it's likely to change in the future.

@gregcaporaso anything you want to add here?

@odetomyday is this something you'd be interested in working on? I'm very flexible on the video and happy to provide more details. Thanks again!

**Comment by odetomyday** [comment]
Thank you for providing more details, and especially pointing me to the example dataset - I was about to put together one of my own and that saves me some work. I believe this is exactly the kind of thing that the instructor of the metagenomics class was looking for in a tutorial video. He had not heard of Keemei so I need to check with him to make sure it does everything he needs it to do for his class, but I suspect that it will. I will let you know if I need any more info to put together a video, and please tell me if you think of any other important points to include.

**Comment by gregcaporaso** [comment]
This all sounds good to me @jairideout.

**Comment by jairideout** [comment]
Sounds good @odetomyday, thanks! Let me know if you or the instructor need more details about Keemei, what it can do, and what its limitations are. It's a very new tool, so not a lot of people are aware of it yet.

Can you let us know if you end up working on the video?

**Comment by odetomyday** [comment]
@jairideout Can I have your email address? The videos will be uploaded tonight but I don't want to make them public until they've been closed captioned and you've given them the OK. I need to "share" the link with you through Youtube.

**Comment by jairideout** [comment]
Awesome!! Can't wait to check out the video. My email address is on my [profile page](https://github.com/jairideout) on the lefthand side.

**Comment by odetomyday** [comment]
I have shared the video with your gmail. As a policy I don't make videos public until my boss has given me the OK and they have been captioned.

**Comment by jairideout** [comment]
@odetomyday :+1: the videos are fantastic, thanks for creating them! These are going to be extremely helpful to new users of Keemei.

Can you let me know when the videos are public so I can start linking to them?

**Comment by gregcaporaso** [comment]
Yes, these are great, thanks so much @odetomyday!

**Comment by odetomyday** [comment]
OK, @jairideout the videos have been captioned and are public :)

**Comment by jairideout** [comment]
Great, thanks for letting me know! I should have time in the next couple of days to link to them from the Keemei website (I'll keep this issue open until then). Thanks again for making these videos @odetomyday!

**Comment by jairideout** [comment]
@odetomyday, I added a new [video section](http://keemei.qiime.org/#videos) to the website with embedded videos. Can you please take a look and let me know if you'd like anything changed (e.g., changes to the NCSU BIT attribution text, direct attribution to you for making the videos, etc.)?

**Comment by gregcaporaso** [comment]
This looks great, thanks again @odetomyday!

**Comment by odetomyday** [comment]
@jairideout Very cool! Could you mention my name, Riley DeHority, in the attribution text? I think I would like to put this in my portfolio. 

Also @gregcaporaso thank you for the stickers :+1:

**Comment by gregcaporaso** [comment]
My pleasure!

**Comment by jairideout** [comment]
@odetomyday the attribution text now includes your name with a link to your personal website. [Take a look](http://keemei.qiime.org/#videos) and let me know if you'd like anything changed. Thanks again for the awesome videos!

Let me know if you end up getting questions about Keemei in the video comments, I'm happy to help answer them (I'm not sure how to get video comment notifications for a video I don't own). You can also refer users to [this section](http://keemei.qiime.org/#help) of the website for getting help with Keemei.

**Comment by odetomyday** [comment]
Looks awesome :) I will let you know if any questions pop up; as far as I
know you can get notifications if you are part of a thread, but not for the
whole video.

**Comment by jairideout** [comment]
Sounds good, thanks again @odetomyday!
