### ISSUE TITLE
HTML service setSandboxMode deprecated

### ISSUE THREAD

**Issue by corburn** [biocore/Keemei#76]
setSandboxMode is probably not required here:

https://github.com/biocore/Keemei/blob/7a9929cb03fcfeb4cac5f62b0e97717da16a5bc4/src/App.gs#L40

> https://developers.google.com/apps-script/
> July 6, 2016
> NATIVE sandbox mode is now shut down. All scripts default to IFRAME mode, regardless of which mode, if any, is specified.

**Comment by jairideout** [comment]
Thanks @corburn! Would you be interested in submitting a PR to remove the line? (I'm excited to have a new set of eyes on the source code too!)

**Comment by corburn** [comment]
Hello @jairideout,

Yes, I will test this out tonight and submit a PR if it works.

**Comment by jairideout** [comment]
Great, thanks!
